# -*- coding: utf-8 -*-

__author__ = 'Nina Mariann Vesseltun'
__email__ = 'nive@nmbu.no'

from random import randint


class ListRand:
    def __init__(self, liste):
        self.liste = liste
        self.current_idx = 0

    def rand(self):
        while True:
            for i in self.liste:
                if self.current_idx < len(self.liste):
                    self.current_idx += 1
                    yield i
                else:
                    raise RuntimeError


class LCGRand:
    slope = 7 ** 5
    congruence_class = 2 ** 31 - 1

    def __init__(self, seed):
        self._hidden_state = seed

    def rand(self):
        self._hidden_state *= self.slope
        self._hidden_state %= self.congruence_class
        return self._hidden_state


    def random_sequence(self, length):
        return RandIter(self, length)

class RandIter:
    def __init__(self, random_number_generator, length):
        self.generator = random_number_generator
        self.length = length
        self.num_generated_numbers = None

    def __iter__(self):
        while True:
            for i in (self.generator).rand():
                yield i

    def __next__(self):
        return next(__iter__())

    def infinite_random_sequence(self, length):
        while True:
            
        return RandIter(self, length)







if __name__ == "__main__":
    numbers = [randint(0, 100) for i in range(5)]
    print(numbers)
    ListRand_classobject = ListRand(numbers)
    ListRand_generatorobject = ListRand_classobject.rand()
    LCGklasse = LCGRand(3)
    LCGgenob = LCGklasse.rand()
    for i in range(len(numbers)):
        print('Generated by ListRand: ', next(ListRand_generatorobject),
              'Generated by LCGRand: ', next(LCGgenob))
